apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
  namespace: streaming-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: content-service

  template:
    metadata:
      labels:
        app: content-service

    spec:
      containers:
        - name: content-service
          image: distributed-streaming-platform/content-service:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8092

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/streaming_contentdb

            - name: SPRING_DATASOURCE_USERNAME
              value: root

            - name: SPRING_DATASOURCE_PASSWORD
              value: yash8252

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka