apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: streaming-platform

data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS streaming_authdb;
    CREATE DATABASE IF NOT EXISTS streaming_userdb;
    CREATE DATABASE IF NOT EXISTS streaming_contentdb;
    CREATE DATABASE IF NOT EXISTS streaming_ingestiondb;
    CREATE DATABASE IF NOT EXISTS streaming_videoprocessingdb;
    CREATE DATABASE IF NOT EXISTS streaming_streamdb;
    CREATE DATABASE IF NOT EXISTS streaming_analyticdb;