apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: streaming-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: distributed-streaming-platform/user-service:v1
          imagePullPolicy: Never

          ports:
            - containerPort: 8091

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/streaming_userdb

            - name: SPRING_DATASOURCE_USERNAME
              value: root

            - name: SPRING_DATASOURCE_PASSWORD
              value: yash8252

            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

            - name: SPRING_DATA_REDIS_HOST
              value: redis

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka