apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: streaming-platform

spec:
  storageClassName: standard
  volumeName: kafka-pv   # 🔥 IMPORTANT

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi